/** -------------------------------------------------- */
/** Example 2 A: State during user-related activities
 */

{
  "auth":
      {"isAuthenticated":true,
      "user":
      {
          "ID":1,
          "Logon":"admin",
          "FirstName":"Admin",
          "isManager":false,
          "isActive":true,
          "ProjectCreate":"true",
          "ProjectRead":"true",
          "ProjectUpdate":"true",
          "ProjectDelete":"true",
          "ProjectApprove":"true",
          "UserCreate":"true",
          "UserRead":"true",
          "UserUpdate":"true",
          "UserDelete":"true",
          "UserApprove":"true",
          "TimeCreate":"true",
          "TimeRead":"true",
          "TimeUpdate":"true",
          "TimeDelete":"true",
          "TimeApprove":"true",
          "IssueCreate":"true",
          "IssueRead":"true",
          "IssueUpdate":"true",
          "IssueDelete":"true",
          "IssueApprove":"true",
          "CommentCreate":"true",
          "CommentRead":"true",
          "CommentUpdate":"true",
          "CommentDelete":"true",
          "CommentApprove":"true",
          "AdminAll":"true",
          "iat":1542582771,
          "exp":1542597171}
      },
      "errors":{},
      "user":
      {
          "userIndiInfo":null,
          "userListUsers":[
              {
                  "ID":1,
                  "Logon":"admin","FirstName":"Admin",
                  "LastName":"Admin","Manager":1,"Department":1,
                  "IsManager":false,"IsActive":true},{"ID":2,
                  "Logon":"warpymx","FirstName":"Mary","LastName":"Warpy",
                  "Manager":1,"Department":1,"IsManager":true,"IsActive":true
              },
              { //...MORE USERS...
                  "ID":2061,"Logon":"truckcx","FirstName":"Cyndi",
                  "LastName":"Truckstruck","Manager":4,"Department":4,
                  "IsManager":false,"IsActive":true
              }
          ],
          "userIndiRoles":[
              {"RoleId":1,"UserHas":true,"RoleName":"AppAdmin"},
              {"RoleId":2,"UserHas":true,"RoleName":"UserMgr"},
              {"RoleId":3,"UserHas":true,"RoleName":"ProjectMgr"},
              {"RoleId":4,"UserHas":true,"RoleName":"TeamMember"},
              {"RoleId":5,"UserHas":true,"RoleName":"IssueInputter"},
              {"RoleId":6,"UserHas":true,"RoleName":"IssueApprover"},
              {"RoleId":7,"UserHas":true,"RoleName":"IssueReader"},
              {"RoleId":8,"UserHas":true,"RoleName":"CommentInputter"},
              {"RoleId":9,"UserHas":true,"RoleName":"CommentApprover"},
              {"RoleId":10,"UserHas":true,"RoleName":"CommentReader"}
          ],
          "userListMgrs":[
              {"ID":2,"FirstName":"Mary","LastName":"Warpy"},
              {"ID":3,"FirstName":"Marge","LastName":"Telly"},
              {"ID":4,"FirstName":"Christopher","LastName":"Hampy"},
              {"ID":13,"FirstName":"Stevei","LastName":"Herslef"},
              {"ID":17,"FirstName":"Test1000","LastName":"Funnyhuh"},
              {"ID":18,"FirstName":"sdjk","LastName":"icnask"},
              {"ID":20,"FirstName":"Hughey","LastName":"Lewis"},
              {"ID":2060,"FirstName":"Billy","LastName":"Bobby"}
          ],
          "userListDepts":[
              {"ID":1,"Name":"Art"},
              {"ID":2,"Name":"Finance"},
              {"ID":3,"Name":"History"},
              {"ID":4,"Name":"English"},
              {"ID":5,"Name":"Pottery"}
          ],
          "userListRoles":[
              {"ID":1,"RoleName":"AppAdmin","UserHas":"false"},
              {"ID":2,"RoleName":"UserMgr","UserHas":"false"},
              {"ID":3,"RoleName":"ProjectMgr","UserHas":"false"},
              {"ID":4,"RoleName":"TeamMember","UserHas":"false"},
              {"ID":5,"RoleName":"IssueInputter","UserHas":"false"},
              {"ID":6,"RoleName":"IssueApprover","UserHas":"false"},
              {"ID":7,"RoleName":"IssueReader","UserHas":"false"},
              {"ID":8,"RoleName":"CommentInputter","UserHas":"false"},
              {"ID":9,"RoleName":"CommentApprover","UserHas":"false"},
              {"ID":10,"RoleName":"CommentReader","UserHas":"false"}
          ],
          "loading":false
        },
          "test":{"uid":null,"loading":false}
}

